---

- name: Push routing configuration to VyOS device
  vyos_config:
    src: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - configure_routing_{{ cloud_vpn_routing }}.j2
      paths:
        - "templates/cloud_vpn/providers/vyos/initiator/{{ cloud_vpn_responder_provider }}"
        - templates/cloud_vpn/providers/vyos/initiator
  delegate_to: initiator
